version: '3.3'
services:
  wordpress:
    image: wordpress:latest
    restart: always
    links:
      - db:mysql
    ports:
      - "80:80"
    working_dir: /var/www/html
    volumes:
      - "/home/wordpress/wp-content:/var/www/html/wp-content"
      - "/home/wordpress/wp:/usr/local/bin/wp"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress333
      WORDPRESS_DB_PASSWORD: wordpress333
      WORDPRESS_DB_NAME: wordpress333
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - "/home/wordpress/mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: wordpress333
      MYSQL_USER: wordpress333
      MYSQL_PASSWORD: wordpress333
